language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key: cebb095d-31a9-4bd3-b130-d2036d330b01
  app: cse-112-tutorial-testing
  on:
    repo: mitcho85/cse112_tutorial_testing
