language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: c248f01f-0117-46e2-a636-148eee0b0b73
  app: cse112_tutorial_testing
  on:
    repo: mitcho85/cse112_tutorial_testing
